### ISSUE TITLE
Error when trying to generate javascript from xml that contains overridden shadows

### ISSUE THREAD

**Issue by AlexejheroYTB** [mo4islona/node-blockly#32]
I'm having an issue saving variables with `node-blockly`. Here is my code:

<details>
<summary>First attempt (code)</summary>

```js
const Blockly = require('node-blockly');

var xml = decodeURIComponent(data.req.body.xml);
var dom = Blockly.Xml.textToDom(xml);
var workspace = new Blockly.Workspace();
Blockly.Xml.domToWorkspace(dom, workspace);
var js = Blockly.JavaScript.workspaceToCode(workspace);
```

</details>

If there are no overridden shadows, the code is generated successfully. But if there are, I get the following error:

<details>
<summary>First attempt (error)</summary>

```
ReferenceError: Element is not defined
    at Object.module.exports.Blockly.Xml.domToVariables (node_modules\node-blockly\lib\blockly_compressed.js:997:93)
    at Object.module.exports.Blockly.Xml.domToWorkspace (node_modules\node-blockly\lib\blockly_compressed.js:991:441)
    at module.exports (src\requests\save.js:45:17)
```

</details>

Upon doing some research, I figured out that `Element` is a DOM interface which is not available in Node.JS, so I installed `jsdom` and `jsdom-global` and changed my code to this:

<details>
<summary>Second attempt (code)</summary>

```js
const Blockly = require('node-blockly');
require('jsdom-global')();

var xml = decodeURIComponent(data.req.body.xml);
var dom = Blockly.Xml.textToDom(xml);
var workspace = new Blockly.Workspace();
Blockly.Xml.domToWorkspace(dom, workspace);
var js = Blockly.JavaScript.workspaceToCode(workspace);
```

</details>

This resulted in the following error: 

<details>
<summary>Second attempt (error)</summary>

```
Error: Trying to set block style to list_blocks before theme was defined via Blockly.setTheme().
    at module.exports.Blockly.Block.setStyle (node_modules\node-blockly\lib\blockly_compressed.js:1465:83)
    at module.exports.Blockly.Block.init (node_modules\node-blockly\lib\blocks_compressed.js:26:511)
    at new module.exports.Blockly.Block (node_modules\node-blockly\lib\blockly_compressed.js:1445:428)
```

</details>

So then I decided to set the style first, changing my code to this:

<details>
<summary>Third attempt (code)</summary>

```js
const Blockly = require('node-blockly');
require('jsdom-global')();

Blockly.setTheme(Blockly.Themes.Classic);
var xml = decodeURIComponent(data.req.body.xml);
var dom = Blockly.Xml.textToDom(xml);
var workspace = new Blockly.Workspace();
Blockly.Xml.domToWorkspace(dom, workspace);
var js = Blockly.JavaScript.workspaceToCode(workspace);
```

</details>

Which then resulted in this error:

<details>
<summary>Third attempt (error)</summary>

```
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at Object.convert (node_modules\node-blockly\node_modules\jsdom\lib\jsdom\living\generated\Node.js:749:11)
    at HTMLUnknownElement.appendChild (node_modules\node-blockly\node_modules\jsdom\lib\jsdom\living\generated\Node.js:280:29)
    at Object.module.exports.Blockly.Xml.blockToDom (node_modules\node-blockly\lib\blockly_compressed.js:12517:54)
```

</details>

The error originates from this statement:

<details>
<summary>Error details</summary>

![image](https://user-images.githubusercontent.com/32238504/60759831-02f70f00-a034-11e9-8f1d-92b2b85a4b45.png)

</details>

After dome debugging, I saw that the type of the parameter was `HTMLUnknownElement`.

I've been trying to fix this for a while but have made no progress, so I decided to open this issue.

---

Running an Express app on Node.JS version 8.15.1

File can be found here: https://github.com/AlexejheroYTB/Dlockly/blob/master/src/requests/save.js

**Comment by mo4islona** [comment]
First of all, library is already use `jsdom` in NodeJS env to avoid errors with missing DOM interfaces.
Could you give an example of xml that throws error?

**Comment by AlexejheroYTB** [comment]
I see that `JSDOM` is required, but still, the `Element` interface is not defined on the global object.

Anyway, I will provide an example xml shortly.

**Comment by AlexejheroYTB** [comment]
This works just fine:

![image](https://user-images.githubusercontent.com/32238504/60760919-87eb2400-a046-11e9-9ddc-77aefbf2b512.png)

```xml
<xml>
  <block type="controls_if" id="hK2]_dlpI+nf6ePQ4kvv" x="49" y="62">
    <value name="IF0">
      <block type="logic_compare" id=":g:5$YT#TQ@-,#`R::k!">
        <field name="OP">EQ</field>
        <value name="A">
          <block type="math_number" id="fBHi1}:k6lXgp6Rf6wQk">
            <field name="NUM">0</field>
          </block>
        </value>
        <value name="B">
          <block type="math_number" id="/h!vy1;=}gShAka/A{/c">
            <field name="NUM">0</field>
          </block>
        </value>
      </block>
    </value>
  </block>
</xml>
```

---

But this does not:

**Comment by AlexejheroYTB** [comment]
Actually, I think I know what this is about. It's about blocks that have OVERWRITTEN shadows

---

This works just fine:

![image](https://user-images.githubusercontent.com/32238504/60760972-d0571180-a047-11e9-9bbc-b809d7f22403.png)

```xml
<xml>
  <block type="controls_if" id="hK2]_dlpI+nf6ePQ4kvv" x="68" y="60">
    <value name="IF0">
      <block type="logic_compare" id=":g:5$YT#TQ@-,#`R::k!">
        <field name="OP">EQ</field>
        <value name="A">
          <block type="math_arithmetic" id="CT/qv/xz7FmADrS7O{(j">
            <field name="OP">ADD</field>
            <value name="A">
              <shadow type="math_number" id="@8XPI]MO`reN!WFIzl13">
                <field name="NUM">1</field>
              </shadow>
            </value>
            <value name="B">
              <shadow type="math_number" id="rsMjwK+M!rD,jb@Drv/H">
                <field name="NUM">1</field>
              </shadow>
            </value>
          </block>
        </value>
        <value name="B">
          <block type="math_number" id="/h!vy1;=}gShAka/A{/c">
            <field name="NUM">2</field>
          </block>
        </value>
      </block>
    </value>
  </block>
</xml>
```

---

But this does not: 

![image](https://user-images.githubusercontent.com/32238504/60760975-e49b0e80-a047-11e9-8403-b7b7b10deaaf.png)

```xml
<xml>
  <block type="controls_if" id="hK2]_dlpI+nf6ePQ4kvv" x="68" y="60">
    <value name="IF0">
      <block type="logic_compare" id=":g:5$YT#TQ@-,#`R::k!">
        <field name="OP">EQ</field>
        <value name="A">
          <block type="math_arithmetic" id="CT/qv/xz7FmADrS7O{(j">
            <field name="OP">ADD</field>
            <value name="A">
              <shadow type="math_number" id="@8XPI]MO`reN!WFIzl13">
                <field name="NUM">1</field>
              </shadow>
              <block type="math_number" id="joHiSo_*L/|GKfZR(meN">
                <field name="NUM">1</field>
              </block>
            </value>
            <value name="B">
              <shadow type="math_number" id="rsMjwK+M!rD,jb@Drv/H">
                <field name="NUM">1</field>
              </shadow>
              <block type="math_number" id="qa$OVK5f1IN/))?-rm8U">
                <field name="NUM">1</field>
              </block>
            </value>
          </block>
        </value>
        <value name="B">
          <block type="math_number" id="/h!vy1;=}gShAka/A{/c">
            <field name="NUM">2</field>
          </block>
        </value>
      </block>
    </value>
  </block>
</xml>
```

**Comment by AlexejheroYTB** [comment]
To clarify, by _"overwritten shadows"_, I mean blocks which have default values (shadows) that have been overwritten with other blocks.

**Comment by mo4islona** [comment]
Please try latest `1.0.38` version

**Comment by AlexejheroYTB** [comment]
Unfortunately I am unable to test it right now, but I will do so as soon as I can.

**Comment by AlexejheroYTB** [comment]
Should I try `1.0.38` or `1.0.40`?

**Comment by AlexejheroYTB** [comment]
Tried `1.0.40`, still the same error:

```
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at Object.convert (node_modules\jsdom\lib\jsdom\living\generated\Node.js:573:11)
    at HTMLUnknownElement.appendChild (node_modules\jsdom\lib\jsdom\living\generated\Node.js:273:31)
    at Object.module.exports.Blockly.Xml.blockToDom (node_modules\node-blockly\lib\blockly_compressed.js:987:24)
    at Object.module.exports.Blockly.Xml.blockToDom (node_modules\node-blockly\lib\blockly_compressed.js:987:95)
    at Object.module.exports.Blockly.Xml.blockToDom (node_modules\node-blockly\lib\blockly_compressed.js:987:95)
    at new module.exports.Blockly.Events.Create (node_modules\node-blockly\lib\blockly_compressed.js:967:172)
    at Object.module.exports.Blockly.Xml.domToBlock (node_modules\node-blockly\lib\blockly_compressed.js:998:243)
    at Object.module.exports.Blockly.Xml.domToWorkspace (node_modules\node-blockly\lib\blockly_compressed.js:993:13)
    at module.exports (src\requests\save.js:49:17)
```

**Comment by AlexejheroYTB** [comment]
If I manually remove the shadow by changing the saved XML, it saves correctly even if I override it.

![image](https://user-images.githubusercontent.com/32238504/60765658-73d70f00-a0a6-11e9-9880-4fd8f30554de.png)

![image](https://user-images.githubusercontent.com/32238504/60765664-8c472980-a0a6-11e9-8c83-07b8cbd54439.png)

**Comment by AlexejheroYTB** [comment]
Do you have any idea on what could be causing this issue? Could it be blocky itself, or just something with the node version?

**Comment by AlexejheroYTB** [comment]
Or, are there any workarounds?

**Comment by AlexejheroYTB** [comment]
I managed to find a workaround for this by manually removing `shadow` elements if there is a `block` element present at the same level.

<details>
<summary>Code</summary>

```js
function removeOverwrittenShadowsRecursively(obj) {
  var shadowElement, blockElement;
  if (obj.elements) {
    for (var element of obj.elements) {
      if (element.name == "shadow") shadowElement = element;
      if (element.name == "block") blockElement = element;
    }
  }

  if (shadowElement && blockElement) removeFromArray(obj.elements, shadowElement);

  if (obj.elements) {
    for (var index in obj.elements) {
      obj.elements[index] = removeOverwrittenShadowsRecursively(obj.elements[index]);
    }
  }

  return obj;
}

function removeFromArray(arr) {
  var what,
    a = arguments,
    L = a.length,
    ax;
  while (L > 1 && arr.length) {
    what = a[--L];
    while ((ax = arr.indexOf(what)) !== -1) {
      arr.splice(ax, 1);
    }
  }
  return arr;
}
```

</details>

Nevertheless, this is still an issue that needs to be resolved with `node-blockly`.

**Comment by mo4islona** [comment]
I`ve added a test with your xml

https://github.com/mo4islona/node-blockly/blob/master/test/js_test.js#L132

Test are passed. No error. It produce `'if (1 + 1 == 2) {\n}\n'` in JS.

**Comment by AlexejheroYTB** [comment]
I have no idea why this is happening. 
I will try this with the latest version.

**Comment by AlexejheroYTB** [comment]
I tried this again with the latest version, but I'm still having the same type error.

**Comment by AlexejheroYTB** [comment]
Closing this due to inactivity. I haven't had this issue in a long time, although I've been using my script.

**Comment by curlyz** [comment]
@AlexejheroYTB  I got the same problem, can you share how to use your script ? Where can I inject that ?

**Comment by Alexejhero** [comment]
Damn, it's been a while since I've touched this project. I'll look over it once I get home.
